let VANILLA = {
    eng: 'This site is coded with pure JavaScript.',
    kor: '이 사이트는 순수 자바스크립트로 코딩되었습니다.'
}

let MAIN_TEXT = {
    eng: [
        'I\'m CHOI YOOJUNG.<br/>I\'m ready now.',
        'Discover',
        'Find out more',
        'Get in touch me!'
    ],
    kor: [
        '안녕하세요, 최유정입니다.<br/>방문을 환영합니다.',
        '보러가기',
        '알아보기',
        '연락하기'
    ]
}

let PROJECT_PREVIEW = {
    eng:{
        description: [
            'Beer recommendation, user review(responsive/PC/mobile)',
            'Beer promotion page(responsive/PC/mobile)',
            'Web page for portfolio(PC)',
            'Ssmall wedding intro web page(responsive/PC/mobile)',
            'Web page for breakfast restaurant(responsive/PC/mobile)'
        ]
    },
    kor: {
        description: [
            '맥주 추천/리뷰, 사용자간 의견 공유(반응형/PC/모바일)',
            '맥주 프로모션 페이지(반응형/PC/모바일)',
            '자기소개 웹 페이지(PC)',
            '스몰 웨딩 소개 웹 페이지(반응형/PC/모바일)',
            '아침 식사 판매 식당(반응형/PC/모바일)'
        ]
    }
}

let PROJECT_DATA = {
    eng:{
        project_1:[
            {
                project_id: 'tobe',
                project_title: [
                    'Today’s Beer', 'planning, web design and publishing'
                ],
                project_info: [
                    {
                        about: 'It\'s a web site designed recommends beer based on various themes so that ordinary people who are interested in beer but are hesitating about which beer to choose can easily choose a beer.<p class="view_file"><a href="doc/tobe_proposal.pdf" download target="_blank">proposal</a><a href="doc/tobe_storyboard.pdf" download target="_blank">storyboard</a><a href="https://www.figma.com/file/V0kHLrF7Y6fjBrWepiKMvq/MyAppPC?node-id=0%3A1" target="_blank">wireframe(Figma)</a><a href="https://www.figma.com/file/B1TmL1pZ4h0n15fV0acg6h/ToBe_Web_Design?node-id=0%3A1" target="_blank">PC design(Figma)</a><a href="https://www.figma.com/file/76nu75LY0rqkacegBKzSDw/Tobe_Mobile?node-id=0%3A1" target="_blank">mobile design(Figma)</a></p>',
                        aim: 'Design without complicity considering user convenience. design responsively in response to changes in resolution, design for tablets and mobile devices',
                        achievements: 'Understanding of the overall flow from planning to design and coding.<br/>Understanding of standard and responsive design<br/>Understanding of Cross-Browsing'
                    }
                ],
                video: 'https://gfycat.com/ifr/NimblePastBlackpanther',
                project_link: 'https://jaicychoi.github.io/tobe',
                github: 'https://github.com/JaicyChoi/tobe',
                languages: [
                    {
                        CSS: 32.8,
                        HTML: 42.1,
                        JavaScript: 25.1
                    }
                ]
            }
        ],
        project_2:[
            {
                project_id: 'samueladams',
                project_title: [
                    'SamuelAdams Boston Lagar', 'web design and publishing'
                ],
                project_info: [
                    {
                        about: 'Introduction and promotion events page for SamuelAdams Boston Lagar. It is designed with reference to the Boston Lager official website.<p class="view_file"><a href="https://www.figma.com/file/u8du0yfjeXBfNrRttX7Si3/Samueladams-Boston-Lagar?node-id=0%3A1" target="_blank">web design(Figma)</a></p>',
                        aim: 'Simple design utilizing margins, Emphasize visual effects with scroll animation, Responsive design considering changes in resolution, Design for tablets and mobile devices.',
                        achievements: 'I realized that creating a smooth animation effect with vanilla JavaScript without a plugin is a bit difficult,<br/>Overall understanding of scroll animation behavior'
                    }
                ],
                video: 'https://gfycat.com/ifr/UntimelyCoordinatedDodo',
                project_link: 'https://jaicychoi.github.io/samueladams',
                github: 'https://github.com/JaicyChoi/samueladams',
                languages: [
                    {
                        CSS: 38.7,
                        HTML: 24.0,
                        JavaScript: 37.3
                    }
                ]
            }
        ],
        project_3:[
            {
                project_id: 'portfolio',
                project_title: [
                    'Profile Page', 'plannig, web design and publishing'
                ],
                project_info: [
                    {
                        about: 'Profile page that introduces the portfolio. The profile page also be a portfolio, so I did do my best. Markup elements are dynamically generated by scripts as needed.<p class="view_file"><a href="https://www.figma.com/file/ofBuy3FdW9mGloX4zUO9Fg/portfolio?node-id=0%3A1" target="_blank">web design(Figma)</a></p>',
                        aim: 'A flat and modern design, A short, simple design that delivers the information a user need, Not gorgeous, but eye-catching animation effect.',
                        achievements: 'Understanding process the creating dynamic elements as them needed.<br/>How to use various visual effects and animations, including svg animations.'
                    }
                ],
                video: 'https://gfycat.com/ifr/PersonalUncomfortableGarpike',
                project_link: 'https://jaicychoi.github.io/portfolio',
                github: 'https://github.com/JaicyChoi/portfolio',
                languages: [
                    {
                        CSS: 31.2,
                        HTML: 19.1,
                        JavaScript: 49.7
                    }
                ]
            }
        ],
        project_4:[
            {
                project_id: 'wedding',
                project_title: [
                    'Little Wedding', 'publishing'
                ],
                project_info: [
                    {
                        about: 'A web page introducing small wedding. This page is based on a free web (PC) design template from <a href="https://www.freepik.com" target="_blank" class="web_address">www.freepik.com</a>, and I\'ve designed and inserted all of the transition and animation effects myself. It\'s a responsive page, so it changes naturally according to the resolution from PC to mobile.<p class="view_file"><a href="https://www.freepik.com/free-psd/elegant-website-templates-wedding_4660026.htm#page=1&query=Web%20templates%20wedding&position=10" target="_blank">web design(freepik)</a></p>',
                        aim: 'Making sure that the mobile pages change naturally based on resolution, even if I don\'t create them separately. Considering cross-browsing to work as well as modern browsers as possible in IE.',
                        achievements: 'The importance of design to respond to a variety of devices considering the response type.'
                    }
                ],
                video: 'https://gfycat.com/ifr/RaggedHarmfulAracari',
                project_link: 'https://jaicychoi.github.io/wedding',
                github: 'https://github.com/JaicyChoi/wedding',
                languages: [
                    {
                        CSS: 60.9,
                        HTML: 24.1,
                        JavaScript: 15.0
                    }
                ]
            }
        ],
        project_5:[
            {
                project_id: 'funny_flakes',
                project_title: [
                    'Funny Flakes', 'publishing'
                ],
                project_info: [
                    {
                        about: 'A restaurant\'s web page that sells breakfast. This page is based on a free web (PC) design template from <a href="https://www.freepik.com" target="_blank" class="web_address">www.freepik.com</a>, and I\'ve designed and inserted all of the transition and animation effects myself. It\'s a responsive page, so it changes naturally according to the resolution from PC to mobile.<br/>The feature is that elements can be moved by drag/touch using Swiper.js.<p class="view_file"><a href="https://www.freepik.com/free-psd/online-publicity-web-template-restaurant_6098102.htm#page=3&query=web+design&position=30" target="_blank">web design(freepik)</a></p>',
                        aim: 'Making sure that the mobile pages change naturally based on resolution, even if I don\'t create them separately. Considering cross-browsing to work as well as modern browsers as possible in IE.',
                        achievements: 'The importance of design to respond to a variety of devices considering the response type.'
                    }
                ],
                video: 'https://gfycat.com/ifr/KnobbyPastIndochinahogdeer',
                project_link: 'https://jaicychoi.github.io/funny_flakes/',
                github: 'https://github.com/JaicyChoi/funny_flakes',
                languages: [
                    {
                        CSS: 58.3,
                        HTML: 30.1,
                        JavaScript: 11.6
                    }
                ]
            }
        ]
    },
    kor:{
        project_1:[
            {
                project_id: 'tobe',
                project_title: [
                    'Today’s Beer', '기획, 웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: '주류 트렌드의 변화로 다양한 맥주가 넘쳐나는 현대사회를 살아가는, 맥주에 관심이 있지만 어떤 맥주를 선택해야할지 고민하는 일반인들이 쉽게 접근할 수 있도록 다양한 테마를 기준으로 맥주를 추천, 맥주 샘플을 신청할 수 있으며 이용자간 의견을 공유하는 사이트 입니다.<p class="view_file"><a href="doc/tobe_proposal.pdf" download target="_blank">proposal</a><a href="doc/tobe_storyboard.pdf" download target="_blank">storyboard</a><a href="https://www.figma.com/file/V0kHLrF7Y6fjBrWepiKMvq/MyAppPC?node-id=0%3A1" target="_blank">wireframe(Figma)</a><a href="https://www.figma.com/file/B1TmL1pZ4h0n15fV0acg6h/ToBe_Web_Design?node-id=0%3A1" target="_blank">PC design(Figma)</a><a href="https://www.figma.com/file/76nu75LY0rqkacegBKzSDw/Tobe_Mobile?node-id=0%3A1" target="_blank">mobile design(Figma)</a></p>',
                        aim: '사용자 편의성을 고려하여 복잡하지 않게 설계하기, 다양한 해상도 변화에 대응한 반응형 사이트로 설계하기, 태블릿 및 모바일 디바이스를 고려하여 설계하기',
                        achievements: '기획부터 코딩에 이르기까지의 전반적인 흐름의 이해,<br/>표준형과 반응형을 고려한 디자인에 대한 이해, 크로스브라우징에 대한 이해'
                    }
                ],
                video: 'https://gfycat.com/ifr/NimblePastBlackpanther',
                project_link:  'https://jaicychoi.github.io/tobe',
                github: 'https://github.com/JaicyChoi/tobe',
                languages: [
                    {
                        CSS: 32.8,
                        HTML: 42.1,
                        JavaScript: 25.1
                    }
                ]
            }
        ],
        project_2:[
            {
                project_id: 'samueladams',
                project_title: [
                    'SamuelAdams Boston Lagar', '웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: 'Boston Brewery의 대표 맥주인 SamuelAdams Boston Lagar에 소개 및 프로모션 이벤트성 페이지로 SamuelAdams Boston Lagar 공식 웹사이트를 참고하여 설계했습니다.<p class="view_file"><a href="https://www.figma.com/file/u8du0yfjeXBfNrRttX7Si3/Samueladams-Boston-Lagar?node-id=0%3A1" target="_blank">web design(Figma)</a></p>',
                        aim: '여백을 활용한 심플한 디자인, 스크롤 애니메이션으로 시각적 효과 강조, 해상도 변화를 고려한 반응형 디자인, 태블릿과 모바일 기기를 고려한 디자인.',
                        achievements: '플러그인이 없이 바닐라 자바스크립트로 부드러운 애니메이션 효과를 만드는 것에 대한 난해함.<br/>스크롤 애니메이션 동작에 대한 전반적인 이해.'
                    }
                ],
                video: 'https://gfycat.com/ifr/UntimelyCoordinatedDodo',
                project_link: 'https://jaicychoi.github.io/samueladams',
                github: 'https://github.com/JaicyChoi/samueladams',
                languages: [
                    {
                        CSS: 38.7,
                        HTML: 24.0,
                        JavaScript: 37.3
                    }
                ]
            }
        ],
        project_3:[
            {
                project_id: 'portfolio',
                project_title: [
                    'Profile Page', '기획, 웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: '포트폴리오를 소개하는 프로필 페이지.  프로필 페이지 또한 하나의 포트폴리오라는 생각으로 만들었습니다. 마크업 요소들을 필요에 따라 스크립트로 동적으로 생성한 부분이 많은 것이 특징입니다.<p class="view_file"><a href="https://www.figma.com/file/ofBuy3FdW9mGloX4zUO9Fg/portfolio?node-id=0%3A1" target="_blank">web design(Figma)</a></p>',
                        aim: '플랫하고 모던한 디자인, 짧고 간단명료하면서 필요한 정보를 전달할 수 있는 디자인, 화려하진 않지만 눈길을 끄는 애니매이션 효과',
                        achievements: '필요에 따른 동적 요소 생성 과정에 대한 이해.<br/>svg 애니메이션을 포함한 다양한 시각적 효과 및 애니메이션 학습.'
                    }
                ],
                video: 'https://gfycat.com/ifr/PersonalUncomfortableGarpike',
                project_link: 'https://jaicychoi.github.io/portfolio',
                github: 'https://github.com/JaicyChoi/portfolio',
                languages: [
                    {
                        CSS: 31.2,
                        HTML: 19.1,
                        JavaScript: 49.7
                    }
                ]
            }
        ],
        project_4:[
            {
                project_id: 'wedding',
                project_title: [
                    'Little Wedding', '퍼블리싱'
                ],
                project_info: [
                    {
                        about: '스몰 웨딩을 소개하는 웹 페이지. <a href="https://www.freepik.com" target="_blank" class="web_address">www.freepik.com</a>에서 무료로 제공하는 웹(PC) 디자인 시안을 바탕으로 작업하였으며, 트랜지션 및 애니매이션 효과는 모두 직접 기획하여 넣었습니다. 반응형 페이지로, PC부터 모바일까지 해상도에 따라 자연스럽게 변하도록 하였습니다.<p class="view_file"><a href="https://www.freepik.com/free-psd/elegant-website-templates-wedding_4660026.htm#page=1&query=Web%20templates%20wedding&position=10" target="_blank">web design(freepik)</a></p>',
                        aim: '모바일 페이지를 따로 제작하지 않더라도 해상도에 따라 자연스럽게 변하도록 하기, IE에서도 최대한 모던 브라우저와 동일하게 작동하도록 크로스 브라우징 고려하기',
                        achievements: '반응형을 고려하여 다양한 기기에 대응할 수 있는 디자인의 중요성'
                    }
                ],
                video: 'https://gfycat.com/ifr/RaggedHarmfulAracari',
                project_link: 'https://jaicychoi.github.io/wedding',
                github: 'https://github.com/JaicyChoi/wedding',
                languages: [
                    {
                        CSS: 60.9,
                        HTML: 24.1,
                        JavaScript: 15.0
                    }
                ]
            }
        ],
        project_5:[
            {
                project_id: 'funny_flakes',
                project_title: [
                    'Funny Flakes', '퍼블리싱'
                ],
                project_info: [
                    {
                        about: '아침 식사 판매를 주류로 하는 식당의 웹 페이지. <a href="https://www.freepik.com" target="_blank" class="web_address">www.freepik.com</a>에서 무료로 제공하는 웹(PC) 디자인 시안을 바탕으로 작업하였으며, 트랜지션 및 애니매이션 효과는 모두 직접 기획하여 넣었습니다. 반응형 페이지로, PC부터 모바일까지 해상도에 따라 자연스럽게 변하도록 하였습니다.<br/>Swiper.js를 사용하여 드래그/터치로 요소를 움직일 수 있게 한 것이 특징입니다.<p class="view_file"><a href="https://www.freepik.com/free-psd/online-publicity-web-template-restaurant_6098102.htm#page=3&query=web+design&position=30" target="_blank">web design(freepik)</a></p>',
                        aim: '모바일 페이지를 따로 제작하지 않더라도 해상도에 따라 자연스럽게 변하도록 하기, IE에서도 최대한 모던 브라우저와 동일하게 작동하도록 크로스 브라우징 고려하기',
                        achievements: '반응형을 고려하여 다양한 기기에 대응할 수 있는 디자인의 중요성'
                    }
                ],
                video: 'https://gfycat.com/ifr/KnobbyPastIndochinahogdeer',
                project_link: 'https://jaicychoi.github.io/funny_flakes/',
                github: 'https://github.com/JaicyChoi/funny_flakes',
                languages: [
                    {
                        CSS: 58.3,
                        HTML: 30.1,
                        JavaScript: 11.6
                    }
                ]
            }
        ]
    }
}

let ABOUT_DATA = {
    eng:{
        intro_text : 'Hello.<br/><br/>I\'m Choi Yoo-jung, want to be a web developer.<br/><br/>I’m rather calm and quiet, thus like jobs which i may set myself a place and focus on, that much i think i have strong concentration.<br/><br/>I\'m trying to listen to other people and develop a sense of tolerance that can accommodate the opinions of people who have different opinions from me.<br/><br/>I\'m interested in new technologies and will continue to learn to adapt to the fast-changing web ecosystem.',
        graph_title: ['Graphic and Web Software', 'Scripting and Programming Language'],
        level: ['BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT'],
        others: [
            'Listening to various themes of music<br/>PC hardware shopping',
            'Video editing(Adobe AE, Premiere pro)<br/>PC(Steam) & console game<br/>Studyng Japanes'
        ],
        aim: [
            {
                C: 'Keep Challenging',
                H: 'To be honest in everything',
                O: 'Listen with an open mind to another\'s',
                I: 'One who drives change and innovation'
            }
        ]
    },
    kor: {
        intro_text : '안녕하세요.<br/><br/>웹 프론트 엔드를 지망하는 최유정입니다.<br/><br/>차분하고 조용한 편으로 가만히 앉아 집중 할 수 있는 일을 선호하며, 그만큼 한 가지 일에 몰두할 때 집중력이 좋습니다.<br/><br/>다른 사람의 말을 귀 기울여 듣고 다른 의견을 가진 사람들의 의견을 수용할 수 있는 포용력을 가진 사람이 되기 위해 노력하고 있습니다.<br/><br/>빠르게 변화하는 웹 생태계에 적응하기 위해 항상 최신 기술에 관심을 가지고 배움을 게을리 하지 않는 엔지니어를 목표로 하고 있습니다.',
        graph_title: ['그래픽 & 웹 소프트웨어', '스트립팅 & 프로그래밍 언어'],
        level: ['초보', '기본', '중급', '고급', '전문가'],
        others: [
            '다양한 장르의 음악 감상하기<br/>PC 주변기기 아이쇼핑',
            '영상 편집(Adobe After Effect, Premire pro)<br/>PC(Steam) & 콘솔 게임<br/>일본어 공부'
        ],
        aim: [
            {
                C: '끊임 없이 도전 하는 사람',
                H: '매사에 정직한 사람',
                O: '다른 사람의 말에 귀 기울이는 사람',
                I: '창의적이고 혁신적인 사고를 하는 사람'
            }
        ]
    },
    graphic_list: [ 350, 190, 210, 140, 270 ],
    programming_list: [ 350, 330, 325, 210 ],
}

let CONTACT = {
    eng:{
        placeholder: ['your name', 'e-mail', 'tell me anything'],
        message: ['Thanks for contacting me!', 'I will get back to you soon!', 're-wrtie'],
        submit: 'Submit'
    },
    kor:{
        placeholder: ['이름', '이메일', '무엇이든 이야기 해주세요'],
        message: ['메시지 감사합니다!', '곧 연락드리겠습니다!', '다시 작성하기'],
        submit: '보내기'
    }
}