let PROJECT_DATA = {
    eng:{
        project_1:[
            {
                project_id: 'tobe',
                project_title: [
                    'Today’s Beer', 'planning, web design and publishing'
                ],
                project_info: [
                    {
                        about: 'It\'s a web site designed recommends beer based on various themes so that ordinary people who are interested in beer but are hesitating about which beer to choose can easily choose a beer.<p class="view_file"><a href="doc/tobe_proposal.pdf" download target="_blank">proposal</a><a href="doc/tobe_storyboard.pdf" download target="_blank">storyboard</a><a href="doc/tobe_web_design.fig" download target="_blank">PC design file(.fig)</a><a href="doc/tobe_mobile_design.fig" download target="_blank">mobile design file(.fig)</a></p>',
                        aim: 'Design without complicity considering user convenience. design responsively in response to changes in resolution, design for tablets and mobile devices',
                        achievements: 'Understanding of the overall flow from planning to design and coding.<br/>Understanding of standard and responsive design'
                    }
                ],
                video: 'https://gfycat.com/ifr/PhysicalScentedErmine',
                project_link: 'https://jaicychoi.github.io/tobe',
                github: 'https://github.com/JaicyChoi/tobe',
                languages: [
                    {
                        CSS: 37.8,
                        HTML: 33.3,
                        JavaScript: 28.9
                    }
                ]
            }
        ],
        project_2:[
            {
                project_id: 'samueladams',
                project_title: [
                    'SamuelAdams Boston Lagar', 'web design and publishing'
                ],
                project_info: [
                    {
                        about: 'Introduction and promotion events page for SamuelAdams Boston Lagar. It is designed with reference to the Boston Lager official website.<p class="view_file"><a href="doc/samueladams_web_design" target="_blank">web design file(.fig)</a></p>',
                        aim: 'Simple design utilizing margins, Emphasize visual effects with scroll animation, Responsive design considering changes in resolution, Design for tablets and mobile devices.',
                        achievements: 'I realized that creating a smooth animation effect with vanilla JavaScript without a plugin is a bit difficult,<br/>Overall understanding of scroll animation behavior'
                    }
                ],
                video: 'https://gfycat.com/ifr/SneakyPoliteKagu',
                project_link: 'https://jaicychoi.github.io/samueladams',
                github: 'https://github.com/JaicyChoi/samueladams',
                languages: [
                    {
                        CSS: 32.1,
                        HTML: 20.1,
                        JavaScript: 47.8
                    }
                ]
            }
        ],
        project_3:[
            {
                project_id: 'portfolio',
                project_title: [
                    'Profile Page', 'plannig, web design and publishing'
                ],
                project_info: [
                    {
                        about: 'Profile page that introduces the portfolio. The profile page also be a portfolio, so I did do my best. Markup elements are dynamically generated by scripts as needed.<p class="view_file"><a href="doc/portfolio_web_design.fig" target="_blank">web design file(.fig)</a></p>',
                        aim: 'A flat and modern design, A short, simple design that delivers the information a user need, Not gorgeous, but eye-catching animation effect.',
                        achievements: 'Understanding process the creating dynamic elements as them needed.<br/>How to use various visual effects and animations, including svg animations.'
                    }
                ],
                video: 'https://gfycat.com/ifr/SneakyPoliteKagu',
                project_link: 'https://jaicychoi.github.io/portfolio',
                github: 'https://github.com/JaicyChoi/portfolio',
                languages: [
                    {
                        CSS: 32.2,
                        HTML: 12.1,
                        JavaScript: 55.7
                    }
                ]
            }
        ]
    },
    kor:{
        project_1:[
            {
                project_id: 'tobe',
                project_title: [
                    'Today’s Beer', '기획, 웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: '주류 트렌드의 변화로 다양한 맥주가 넘쳐나는 현대사회를 살아가는, 맥주에 관심이 있지만 어떤 맥주를 선택해야할지 고민하는 일반인들이 쉽게 접근할 수 있도록 다양한 테마를 기준으로 맥주를 추천, 맥주 샘플을 신청할 수 있으며 이용자간 의견을 공유하는 사이트 입니다.<p class="view_file"><a href="doc/tobe_proposal.pdf" download target="_blank">기획서</a><a href="doc/tobe_storyboard.pdf" download target="_blank">스토리보드</a><a href="doc/tobe_web_design.fig" download target="_blank">PC 디자인 파일(.fig)</a><a href="doc/tobe_mobile_design.fig" download target="_blank">모바일 디자인 파일(.fig)</a></p>',
                        aim: '사용자 편의성을 고려하여 복잡하지 않게 설계하기, 다양한 해상도 변화에 대응한 반응형 사이트로 설계하기, 태블릿 및 모바일 디바이스를 고려하여 설계하기',
                        achievements: '기획부터 코딩에 이르기까지의 전반적인 흐름의 이해,<br/>표준형과 반응형을 고려한 디자인에 대한 이해'
                    }
                ],
                video: 'https://gfycat.com/ifr/PhysicalScentedErmine',
                project_link:  'https://jaicychoi.github.io/tobe',
                github: 'https://github.com/JaicyChoi/tobe',
                languages: [
                    {
                        CSS: 38.8,
                        HTML: 31.1,
                        JavaScript: 28.9
                    }
                ]
            }
        ],
        project_2:[
            {
                project_id: 'samueladams',
                project_title: [
                    'SamuelAdams Boston Lagar', '웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: 'Boston Brewery의 대표 맥주인 SamuelAdams Boston Lagar에 소개 및 프로모션 이벤트성 페이지로 SamuelAdams Boston Lagar 공식 웹사이트를 참고하여 설계했습니다.<p class="view_file"><a href="doc/samueladams_web_design.fig" target="_blank">웹 디자인 파일(.fig)</a></p>',
                        aim: '여백을 활용한 심플한 디자인, 스크롤 애니메이션으로 시각적 효과 강조, 해상도 변화를 고려한 반응형 디자인, 태블릿과 모바일 기기를 고려한 디자인.',
                        achievements: '플러그인이 없이 바닐라 자바스크립트로 부드러운 애니메이션 효과를 만드는 것에 대한 난해함.<br/>스크롤 애니메이션 동작에 대한 전반적인 이해.'
                    }
                ],
                video: 'https://gfycat.com/ifr/SneakyPoliteKagu',
                project_link: 'https://jaicychoi.github.io/samueladams',
                github: 'https://github.com/JaicyChoi/samueladams',
                languages: [
                    {
                        CSS: 32.1,
                        HTML: 20.1,
                        JavaScript: 47.8
                    }
                ]
            }
        ],
        project_3:[
            {
                project_id: 'portfolio',
                project_title: [
                    'Profile Page', '기획, 웹 디자인, 퍼블리싱'
                ],
                project_info: [
                    {
                        about: '포트폴리오를 소개하는 프로필 페이지.  프로필 페이지 또한 하나의 포트폴리오라는 생각으로 만들었습니다. 마크업 요소들을 필요에 따라 스크립트로 동적으로 생성한 부분이 많은 것이 특징입니다.<p class="view_file"><a href="doc/portfolio_web_design.fig" target="_blank">웹 디자인 파일(.fig)</a></p>',
                        aim: '플랫하고 모던한 디자인, 짧고 간단명료하면서 필요한 정보를 전달할 수 있는 디자인, 화려하진 않지만 눈길을 끄는 애니매이션 효과',
                        achievements: '필요에 따른 동적 요소 생성 과정에 대한 이해.<br/>svg 애니메이션을 포함한 다양한 시각적 효과 및 애니메이션 학습.'
                    }
                ],
                video: 'https://gfycat.com/ifr/SneakyPoliteKagu',
                project_link: 'https://jaicychoi.github.io/portfolio',
                github: 'https://github.com/JaicyChoi/portfolio',
                languages: [
                    {
                        CSS: 32.2,
                        HTML: 12.1,
                        JavaScript: 55.7
                    }
                ]
            }
        ]
    }
}

let ABOUT_DATA = {
    eng:{
        intro_text1 : 'Hello.<br/><br/>I\'m Choi Yoo-jung, want to be a web publisher.<br/><br/>I’m rather calm and quiet, thus like jobs which i may set myself a place and focus on, that much i think i have strong concentration.<br/><br/>I\'m trying to listen to other people and develop a sense of tolerance that can accommodate the opinions of people who have different opinions from me.<br/><br/>I\'m interested in new technologies and will continue to learn to adapt to the fast-changing web ecosystem.',
        intro_text2: '<span class="bold">Skills</span> : Web Design, HTML, CSS, JavaScript, Git<br/><br/>I like : Listening to various themes of music, PC hardware shopping<br/><br/>I interested in : Video editing(Adobe AE, Premire pro), PC(Steam) & console game, Studying Japanese',
        aim: [
            {
                C: 'Keep Challenging',
                H: 'To be honest in everything',
                O: 'Listen with an open mind to another\'s',
                I: 'One who drives change and innovation'
            }
        ]
    },
    kor: {
        intro_text1 : '안녕하세요.<br/><br/>웹 퍼블리셔를 지망하는 최유정입니다.<br/><br/>차분하고 조용한 편으로 가만히 앉아 집중 할 수 있는 일을 선호하며, 그만큼 한 가지 일에 몰두할 때 집중력이 좋습니다.<br/><br/>다른 사람의 말을 귀 기울여 듣고 다른 의견을 가진 사람들의 의견을 수용할 수 있는 포용력을 가진 사람이 되기 위해 노력하고 있습니다.<br/><br/>빠르게 변화하는 웹 생태계에 적응하기 위해 항상 최신 기술에 관심을 가지고 배움을 게을리 하지 않는 엔지니어를 목표로 하고 있습니다.',
        intro_text2: '<span class="bold">Skills</span> : Web design, HTML, CSS, JavaScript, Git<br/><br/>I like : 다양한 장르의 음악 감상하기, PC 주변기기 아이쇼핑<br/><br/>I interested in : 영상 편집(Adobe After Effect, Premire pro), PC(Steam) & 콘솔 게임, 일본어 공부',
        aim: [
            {
                C: '끊임 없이 도전 하는 사람',
                H: '매사에 정직한 사람',
                O: '다른 사람의 말에 귀 기울이는 사람',
                I: '창의적이고 혁신적인 사고를 하는 사람'
            }
        ]
    }
}

let CONTACT = {
    eng:{
        message: ['Thanks for contacting me!', 'I will get back to you soon!', 're-wrtie']
    },
    kor:{
        message: ['메시지 감사합니다!', '곧 연락드리겠습니다!', '다시 작성하기']
    }
}